name: kraya_backend
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.1 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.3 
  lints: ^2.0.0
  mockito: ^5.3.2
  test: ^1.22.1 

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: any
  get_it: ^7.2.0
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
